//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try font.validate()
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 24 colors.
  struct color {
    /// Color `destructionButtonsColor`.
    static let destructionButtonsColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "destructionButtonsColor")
    /// Color `primaryBackgroundColor`.
    static let primaryBackgroundColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "primaryBackgroundColor")
    /// Color `primaryButtonBackgroundColor`.
    static let primaryButtonBackgroundColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "primaryButtonBackgroundColor")
    /// Color `primaryButtonIconColor`.
    static let primaryButtonIconColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "primaryButtonIconColor")
    /// Color `primaryButtonTextColor`.
    static let primaryButtonTextColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "primaryButtonTextColor")
    /// Color `primaryTextColor`.
    static let primaryTextColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "primaryTextColor")
    /// Color `secondaryBackgroundColor`.
    static let secondaryBackgroundColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "secondaryBackgroundColor")
    /// Color `secondaryButtonBackgroundColor`.
    static let secondaryButtonBackgroundColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "secondaryButtonBackgroundColor")
    /// Color `secondaryButtonBorderColor`.
    static let secondaryButtonBorderColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "secondaryButtonBorderColor")
    /// Color `secondaryButtonIconColor`.
    static let secondaryButtonIconColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "secondaryButtonIconColor")
    /// Color `secondaryButtonTextColor`.
    static let secondaryButtonTextColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "secondaryButtonTextColor")
    /// Color `secondaryTextColor`.
    static let secondaryTextColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "secondaryTextColor")
    /// Color `shadow`.
    static let shadow = Rswift.ColorResource(bundle: R.hostingBundle, name: "shadow")
    /// Color `textButtonTextColor`.
    static let textButtonTextColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textButtonTextColor")
    /// Color `textFieldBackgroundColor`.
    static let textFieldBackgroundColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldBackgroundColor")
    /// Color `textFieldBorderColor`.
    static let textFieldBorderColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldBorderColor")
    /// Color `textFieldErrorBorderColor`.
    static let textFieldErrorBorderColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldErrorBorderColor")
    /// Color `textFieldErrorHintColor`.
    static let textFieldErrorHintColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldErrorHintColor")
    /// Color `textFieldErrorIconColor`.
    static let textFieldErrorIconColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldErrorIconColor")
    /// Color `textFieldErrorTextColor`.
    static let textFieldErrorTextColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldErrorTextColor")
    /// Color `textFieldHintColor`.
    static let textFieldHintColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldHintColor")
    /// Color `textFieldPlaceholderTextColor`.
    static let textFieldPlaceholderTextColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldPlaceholderTextColor")
    /// Color `textFieldPrimaryIconColor`.
    static let textFieldPrimaryIconColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldPrimaryIconColor")
    /// Color `textFieldTextColor`.
    static let textFieldTextColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "textFieldTextColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "destructionButtonsColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func destructionButtonsColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.destructionButtonsColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "primaryBackgroundColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func primaryBackgroundColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.primaryBackgroundColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "primaryButtonBackgroundColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func primaryButtonBackgroundColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.primaryButtonBackgroundColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "primaryButtonIconColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func primaryButtonIconColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.primaryButtonIconColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "primaryButtonTextColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func primaryButtonTextColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.primaryButtonTextColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "primaryTextColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func primaryTextColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.primaryTextColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "secondaryBackgroundColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondaryBackgroundColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondaryBackgroundColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "secondaryButtonBackgroundColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondaryButtonBackgroundColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondaryButtonBackgroundColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "secondaryButtonBorderColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondaryButtonBorderColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondaryButtonBorderColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "secondaryButtonIconColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondaryButtonIconColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondaryButtonIconColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "secondaryButtonTextColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondaryButtonTextColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondaryButtonTextColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "secondaryTextColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondaryTextColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondaryTextColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "shadow", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func shadow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.shadow, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textButtonTextColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textButtonTextColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textButtonTextColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldBackgroundColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldBackgroundColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldBackgroundColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldBorderColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldBorderColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldBorderColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldErrorBorderColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldErrorBorderColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldErrorBorderColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldErrorHintColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldErrorHintColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldErrorHintColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldErrorIconColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldErrorIconColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldErrorIconColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldErrorTextColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldErrorTextColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldErrorTextColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldHintColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldHintColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldHintColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldPlaceholderTextColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldPlaceholderTextColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldPlaceholderTextColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldPrimaryIconColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldPrimaryIconColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldPrimaryIconColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "textFieldTextColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textFieldTextColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textFieldTextColor, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 12 files.
  struct file {
    /// Resource file `Cairo-Black.ttf`.
    static let cairoBlackTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Cairo-Black", pathExtension: "ttf")
    /// Resource file `Cairo-Bold.ttf`.
    static let cairoBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Cairo-Bold", pathExtension: "ttf")
    /// Resource file `Cairo-ExtraLight.ttf`.
    static let cairoExtraLightTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Cairo-ExtraLight", pathExtension: "ttf")
    /// Resource file `Cairo-Light.ttf`.
    static let cairoLightTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Cairo-Light", pathExtension: "ttf")
    /// Resource file `Cairo-Regular.ttf`.
    static let cairoRegularTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Cairo-Regular", pathExtension: "ttf")
    /// Resource file `Cairo-SemiBold.ttf`.
    static let cairoSemiBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Cairo-SemiBold", pathExtension: "ttf")
    /// Resource file `Poppins-Black.ttf`.
    static let poppinsBlackTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Poppins-Black", pathExtension: "ttf")
    /// Resource file `Poppins-Bold.ttf`.
    static let poppinsBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Poppins-Bold", pathExtension: "ttf")
    /// Resource file `Poppins-ExtraLight.ttf`.
    static let poppinsExtraLightTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Poppins-ExtraLight", pathExtension: "ttf")
    /// Resource file `Poppins-Light.ttf`.
    static let poppinsLightTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Poppins-Light", pathExtension: "ttf")
    /// Resource file `Poppins-Regular.ttf`.
    static let poppinsRegularTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Poppins-Regular", pathExtension: "ttf")
    /// Resource file `Poppins-SemiBold.ttf`.
    static let poppinsSemiBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Poppins-SemiBold", pathExtension: "ttf")

    /// `bundle.url(forResource: "Cairo-Black", withExtension: "ttf")`
    static func cairoBlackTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cairoBlackTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Cairo-Bold", withExtension: "ttf")`
    static func cairoBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cairoBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Cairo-ExtraLight", withExtension: "ttf")`
    static func cairoExtraLightTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cairoExtraLightTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Cairo-Light", withExtension: "ttf")`
    static func cairoLightTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cairoLightTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Cairo-Regular", withExtension: "ttf")`
    static func cairoRegularTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cairoRegularTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Cairo-SemiBold", withExtension: "ttf")`
    static func cairoSemiBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cairoSemiBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Poppins-Black", withExtension: "ttf")`
    static func poppinsBlackTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.poppinsBlackTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Poppins-Bold", withExtension: "ttf")`
    static func poppinsBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.poppinsBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Poppins-ExtraLight", withExtension: "ttf")`
    static func poppinsExtraLightTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.poppinsExtraLightTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Poppins-Light", withExtension: "ttf")`
    static func poppinsLightTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.poppinsLightTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Poppins-Regular", withExtension: "ttf")`
    static func poppinsRegularTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.poppinsRegularTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Poppins-SemiBold", withExtension: "ttf")`
    static func poppinsSemiBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.poppinsSemiBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.font` struct is generated, and contains static references to 12 fonts.
  struct font: Rswift.Validatable {
    /// Font `Cairo-Black`.
    static let cairoBlack = Rswift.FontResource(fontName: "Cairo-Black")
    /// Font `Cairo-Bold`.
    static let cairoBold = Rswift.FontResource(fontName: "Cairo-Bold")
    /// Font `Cairo-ExtraLight`.
    static let cairoExtraLight = Rswift.FontResource(fontName: "Cairo-ExtraLight")
    /// Font `Cairo-Light`.
    static let cairoLight = Rswift.FontResource(fontName: "Cairo-Light")
    /// Font `Cairo-Regular`.
    static let cairoRegular = Rswift.FontResource(fontName: "Cairo-Regular")
    /// Font `Cairo-SemiBold`.
    static let cairoSemiBold = Rswift.FontResource(fontName: "Cairo-SemiBold")
    /// Font `Poppins-Black`.
    static let poppinsBlack = Rswift.FontResource(fontName: "Poppins-Black")
    /// Font `Poppins-Bold`.
    static let poppinsBold = Rswift.FontResource(fontName: "Poppins-Bold")
    /// Font `Poppins-ExtraLight`.
    static let poppinsExtraLight = Rswift.FontResource(fontName: "Poppins-ExtraLight")
    /// Font `Poppins-Light`.
    static let poppinsLight = Rswift.FontResource(fontName: "Poppins-Light")
    /// Font `Poppins-Regular`.
    static let poppinsRegular = Rswift.FontResource(fontName: "Poppins-Regular")
    /// Font `Poppins-SemiBold`.
    static let poppinsSemiBold = Rswift.FontResource(fontName: "Poppins-SemiBold")

    /// `UIFont(name: "Cairo-Black", size: ...)`
    static func cairoBlack(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: cairoBlack, size: size)
    }

    /// `UIFont(name: "Cairo-Bold", size: ...)`
    static func cairoBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: cairoBold, size: size)
    }

    /// `UIFont(name: "Cairo-ExtraLight", size: ...)`
    static func cairoExtraLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: cairoExtraLight, size: size)
    }

    /// `UIFont(name: "Cairo-Light", size: ...)`
    static func cairoLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: cairoLight, size: size)
    }

    /// `UIFont(name: "Cairo-Regular", size: ...)`
    static func cairoRegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: cairoRegular, size: size)
    }

    /// `UIFont(name: "Cairo-SemiBold", size: ...)`
    static func cairoSemiBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: cairoSemiBold, size: size)
    }

    /// `UIFont(name: "Poppins-Black", size: ...)`
    static func poppinsBlack(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: poppinsBlack, size: size)
    }

    /// `UIFont(name: "Poppins-Bold", size: ...)`
    static func poppinsBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: poppinsBold, size: size)
    }

    /// `UIFont(name: "Poppins-ExtraLight", size: ...)`
    static func poppinsExtraLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: poppinsExtraLight, size: size)
    }

    /// `UIFont(name: "Poppins-Light", size: ...)`
    static func poppinsLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: poppinsLight, size: size)
    }

    /// `UIFont(name: "Poppins-Regular", size: ...)`
    static func poppinsRegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: poppinsRegular, size: size)
    }

    /// `UIFont(name: "Poppins-SemiBold", size: ...)`
    static func poppinsSemiBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: poppinsSemiBold, size: size)
    }

    static func validate() throws {
      if R.font.cairoBlack(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Cairo-Black' could not be loaded, is 'Cairo-Black.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.cairoBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Cairo-Bold' could not be loaded, is 'Cairo-Bold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.cairoExtraLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Cairo-ExtraLight' could not be loaded, is 'Cairo-ExtraLight.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.cairoLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Cairo-Light' could not be loaded, is 'Cairo-Light.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.cairoRegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Cairo-Regular' could not be loaded, is 'Cairo-Regular.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.cairoSemiBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Cairo-SemiBold' could not be loaded, is 'Cairo-SemiBold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.poppinsBlack(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Poppins-Black' could not be loaded, is 'Poppins-Black.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.poppinsBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Poppins-Bold' could not be loaded, is 'Poppins-Bold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.poppinsExtraLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Poppins-ExtraLight' could not be loaded, is 'Poppins-ExtraLight.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.poppinsLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Poppins-Light' could not be loaded, is 'Poppins-Light.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.poppinsRegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Poppins-Regular' could not be loaded, is 'Poppins-Regular.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.poppinsSemiBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Poppins-SemiBold' could not be loaded, is 'Poppins-SemiBold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
    }

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizables` struct is generated, and contains static references to 10 localization keys.
    struct localizables {
      /// en translation: Names can't contain emojis.
      ///
      /// Locales: ar, en
      static let names_cant_contain_emojis = Rswift.StringResource(key: "names_cant_contain_emojis", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: Names can't contain numbers.
      ///
      /// Locales: ar, en
      static let names_cant_contain_numbers = Rswift.StringResource(key: "names_cant_contain_numbers", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: Names can't contain special characters.
      ///
      /// Locales: ar, en
      static let names_cant_contain_special_characters = Rswift.StringResource(key: "names_cant_contain_special_characters", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: Oops... Something went wrong!
      ///
      /// Locales: ar, en
      static let generic_error = Rswift.StringResource(key: "generic_error", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: Password is too short.
      ///
      /// Locales: ar, en
      static let password_too_short = Rswift.StringResource(key: "password_too_short", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: The %@ can't be empty.
      ///
      /// Locales: ar, en
      static let field_cant_be_empty = Rswift.StringResource(key: "field_cant_be_empty", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: This email is not valid.
      ///
      /// Locales: ar, en
      static let email_not_valid = Rswift.StringResource(key: "email_not_valid", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: Your Super Secret Password.
      ///
      /// Locales: ar, en
      static let password_hint_unlocked = Rswift.StringResource(key: "password_hint_unlocked", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: Your current password
      ///
      /// Locales: ar, en
      static let your_current_password = Rswift.StringResource(key: "your_current_password", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)
      /// en translation: ••••••••••••••••••••••••••
      ///
      /// Locales: ar, en
      static let password_hint_locked = Rswift.StringResource(key: "password_hint_locked", tableName: "Localizables", bundle: R.hostingBundle, locales: ["ar", "en"], comment: nil)

      /// en translation: Names can't contain emojis.
      ///
      /// Locales: ar, en
      static func names_cant_contain_emojis(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("names_cant_contain_emojis", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "names_cant_contain_emojis"
        }

        return NSLocalizedString("names_cant_contain_emojis", tableName: "Localizables", bundle: bundle, comment: "")
      }

      /// en translation: Names can't contain numbers.
      ///
      /// Locales: ar, en
      static func names_cant_contain_numbers(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("names_cant_contain_numbers", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "names_cant_contain_numbers"
        }

        return NSLocalizedString("names_cant_contain_numbers", tableName: "Localizables", bundle: bundle, comment: "")
      }

      /// en translation: Names can't contain special characters.
      ///
      /// Locales: ar, en
      static func names_cant_contain_special_characters(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("names_cant_contain_special_characters", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "names_cant_contain_special_characters"
        }

        return NSLocalizedString("names_cant_contain_special_characters", tableName: "Localizables", bundle: bundle, comment: "")
      }

      /// en translation: Oops... Something went wrong!
      ///
      /// Locales: ar, en
      static func generic_error(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("generic_error", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "generic_error"
        }

        return NSLocalizedString("generic_error", tableName: "Localizables", bundle: bundle, comment: "")
      }

      /// en translation: Password is too short.
      ///
      /// Locales: ar, en
      static func password_too_short(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("password_too_short", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "password_too_short"
        }

        return NSLocalizedString("password_too_short", tableName: "Localizables", bundle: bundle, comment: "")
      }

      /// en translation: The %@ can't be empty.
      ///
      /// Locales: ar, en
      static func field_cant_be_empty(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("field_cant_be_empty", tableName: "Localizables", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "field_cant_be_empty"
        }

        let format = NSLocalizedString("field_cant_be_empty", tableName: "Localizables", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: This email is not valid.
      ///
      /// Locales: ar, en
      static func email_not_valid(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("email_not_valid", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "email_not_valid"
        }

        return NSLocalizedString("email_not_valid", tableName: "Localizables", bundle: bundle, comment: "")
      }

      /// en translation: Your Super Secret Password.
      ///
      /// Locales: ar, en
      static func password_hint_unlocked(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("password_hint_unlocked", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "password_hint_unlocked"
        }

        return NSLocalizedString("password_hint_unlocked", tableName: "Localizables", bundle: bundle, comment: "")
      }

      /// en translation: Your current password
      ///
      /// Locales: ar, en
      static func your_current_password(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("your_current_password", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "your_current_password"
        }

        return NSLocalizedString("your_current_password", tableName: "Localizables", bundle: bundle, comment: "")
      }

      /// en translation: ••••••••••••••••••••••••••
      ///
      /// Locales: ar, en
      static func password_hint_locked(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("password_hint_locked", tableName: "Localizables", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizables", preferredLanguages: preferredLanguages) else {
          return "password_hint_locked"
        }

        return NSLocalizedString("password_hint_locked", tableName: "Localizables", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
